tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "go-delve/delve"
tap "caskroom/fonts"
tap "caskroom/cask"
tap "dart-lang/dart"
tap "neovim/neovim"
brew "ack"
brew "automake"
brew "bash"
brew "binutils"
brew "ccat"
brew "clisp"
brew "cocoapods"
brew "coreutils"
brew "cpanminus"
brew "ctags"
brew "go"
brew "dep"
brew "dialog"
brew "editorconfig"
brew "elixir"
brew "exercism"
brew "ffmpeg"
brew "findutils", args: ["with-default-names"]
brew "fish"
brew "pkg-config"
brew "fontforge"
brew "gawk"
brew "gnu-indent", args: ["with-default-names"]
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-which", args: ["with-default-names"]
brew "gnutls"
brew "gradle"
brew "grip"
brew "guile"
brew "hadolint"
brew "hh"
brew "hugo"
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "ios-deploy"
brew "jq"
brew "kotlin"
brew "leiningen"
brew "libcello"
brew "libksba"
brew "libyaml"
brew "python"
brew "macvim"
brew "make"
brew "mit-scheme"
brew "nasm"
brew "neovim"
brew "openssl@1.1"
brew "pandoc"
brew "perl"
brew "privoxy", restart_service: true
brew "rakudo-star"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "ruby"
brew "rust"
brew "shellcheck"
brew "textql"
brew "tmate"
brew "tmux"
brew "tree"
brew "vegeta"
brew "watch"
brew "watchman"
brew "wdiff", args: ["with-gettext"]
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "dart-lang/dart/dart", args: ["with-content-shell", "with-dartium"]
brew "go-delve/delve/delve"
cask "alcatraz"
cask "minikube"
cask "ngrok"
cask "caskroom/fonts/font-fira-code"
cask "caskroom/fonts/font-firacode-nerd-font-mono"
cask "caskroom/fonts/font-hack-nerd-font"
